name: ParinaCoreLibrary
description: Provides cool shit for shit server!
version: 1.0-DEV

author: isokissa3
website: https://joniaromaa.fi

load: STARTUP
softdepend: [ProtocolLib, Citizens]

main: fi.joniaromaa.parinacorelibrary.bukkit.ParinaCoreBukkitPluginLoader